[project]
name = "my-app-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.6",
    "psycopg[binary]>=3.2.10",
    "pypdf>=6.1.0",
    "python-decouple>=3.8",
]
